[package]
name = "werewolves-and-wanderer"
version = "0.1.0"
authors = ["Atul Varma <varmaa@gmail.com>"]

[lib]
name = "ww"

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
rand = "0.3"

[dependencies]
enum_primitive = "0.1.1"
